'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { API_URL } from '../lib/config';
import { deviceIcon,deviceName,formatRelative } from '../lib/format';
import type { Bot,PrivacySettings,Session,User } from '../lib/types';
import { Avatar } from './Avatar';
import { Modal,dialogs } from './ui';
export default function SettingsModal({ token, me, api, onMeUpdated, onClose }: {
  token: string; me: User; api: <T>(path: string, init?: RequestInit) => Promise<T>; onMeUpdated: (user: User) => void; onClose: () => void;
}) {
  type Passkey = { id: string; name: string; deviceType: string; backedUp: boolean; createdAt: string; lastUsedAt: string | null };
  const [page, setPage] = useState('profile');
  const [sessions, setSessions] = useState<Session[]>([]);
  const [blockedUsers, setBlockedUsers] = useState<User[]>([]);
  const [bots, setBots] = useState<Bot[]>([]);
  const [freshBotToken, setFreshBotToken] = useState<string | null>(null);
  const [security, setSecurity] = useState<{ twoFactorEnabled: boolean; passkeys: Passkey[] }>({ twoFactorEnabled: false, passkeys: [] });
  const [privacy, setPrivacy] = useState<PrivacySettings>({ lastSeen: 'everyone', calls: 'everyone', groups: 'everyone', readReceipts: true });
  const [totpSetup, setTotpSetup] = useState<{ setupId: string; secret: string; uri: string } | null>(null);
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [totpCode, setTotpCode] = useState('');
  const [theme, setTheme] = useState(() => typeof window !== 'undefined' ? (window.localStorage.getItem('messenger_theme') || 'midnight') : 'midnight');
  const [displayName, setDisplayName] = useState(me.displayName);
  const [bio, setBio] = useState(me.bio || '');
  const [avatarMediaId, setAvatarMediaId] = useState<string | null>(me.avatarMediaId);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const avatarInput = useRef<HTMLInputElement | null>(null);

  const load = useCallback(async () => {
    try {
      const [sessionData, blockData, botData, securityData, privacyData] = await Promise.all([
        api<{ sessions: Session[] }>('/auth/sessions'), api<{ users: User[] }>('/blocks'), api<{ bots: Bot[] }>('/bots'),
        api<{ twoFactorEnabled: boolean; passkeys: Passkey[] }>('/security'), api<{ privacy: PrivacySettings }>('/privacy'),
      ]);
      setSessions(sessionData.sessions); setBlockedUsers(blockData.users); setBots(botData.bots); setSecurity(securityData); setPrivacy(privacyData.privacy);
    } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка'); }
  }, [api]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { document.documentElement.dataset.theme = theme; window.localStorage.setItem('messenger_theme', theme); }, [theme]);

  const saveProfile = async () => { setBusy(true); setError(''); try { const data = await api<{ user: User }>('/me', { method: 'PATCH', body: JSON.stringify({ displayName, bio, avatarMediaId }) }); window.localStorage.setItem('messenger_user', JSON.stringify(data.user)); onMeUpdated(data.user); } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка сохранения профиля'); } finally { setBusy(false); } };
  const uploadAvatar = async (file: File) => { setBusy(true); setError(''); try { if (!file.type.startsWith('image/')) throw new Error('Для аватара выбери изображение.'); const response = await fetch(`${API_URL}/media`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': file.type, 'X-File-Name': encodeURIComponent(file.name) }, body: file }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Не удалось загрузить аватар'); if (!/^image\/(png|jpeg|gif|webp)$/.test(data.media.mimeType)) throw new Error('Выбери PNG, JPEG, GIF или WebP.'); setAvatarMediaId(data.media.id); } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка аватара'); } finally { setBusy(false); if (avatarInput.current) avatarInput.current.value = ''; } };
  const terminate = async (id: string) => { setBusy(true); try { await api(`/auth/sessions/${id}`, { method: 'DELETE' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка'); } finally { setBusy(false); } };
  const terminateOthers = async () => { setBusy(true); try { await api('/auth/sessions/others', { method: 'DELETE' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка'); } finally { setBusy(false); } };
  const unblock = async (user: User) => { try { await api(`/users/${encodeURIComponent(user.username)}/block`, { method: 'DELETE' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось разблокировать'); } };

  const start2fa = async () => { setBusy(true); setError(''); try { setTotpSetup(await api('/security/2fa/setup', { method: 'POST' })); setTotpCode(''); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось включить 2FA'); } finally { setBusy(false); } };
  const confirm2fa = async () => { if (!totpSetup) return; setBusy(true); try { const data = await api<{ recoveryCodes: string[] }>('/security/2fa/confirm', { method: 'POST', body: JSON.stringify({ setupId: totpSetup.setupId, code: totpCode }) }); setRecoveryCodes(data.recoveryCodes); setTotpSetup(null); setTotpCode(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Неверный код'); } finally { setBusy(false); } };
  const disable2fa = async () => { const code = (await dialogs.prompt('Код из приложения-аутентификатора')); if (!code) return; setBusy(true); try { await api('/security/2fa/disable', { method: 'POST', body: JSON.stringify({ code }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось отключить 2FA'); } finally { setBusy(false); } };
  const addPasskey = async () => { setBusy(true); setError(''); try { const data = await api<{ challengeId: string; options: unknown }>('/security/passkeys/options'); const { startRegistration } = await import('@simplewebauthn/browser'); const response = await startRegistration({ optionsJSON: data.options as never }); const name = (await dialogs.prompt('Название Passkey', 'Это устройство')) || 'Passkey'; await api('/security/passkeys/verify', { method: 'POST', body: JSON.stringify({ challengeId: data.challengeId, response, name }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось создать Passkey'); } finally { setBusy(false); } };
  const removePasskey = async (id: string) => { try { await api(`/security/passkeys/${id}`, { method: 'DELETE' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось удалить Passkey'); } };
  const savePrivacy = async (patch: Partial<PrivacySettings>) => { const next = { ...privacy, ...patch }; const previous = privacy; setPrivacy(next); try { const data = await api<{ privacy: PrivacySettings }>('/privacy', { method: 'PATCH', body: JSON.stringify(next) }); setPrivacy(data.privacy); } catch (e) { setPrivacy(previous); setError(e instanceof Error ? e.message : 'Не удалось сохранить приватность'); } };

  const createBot = async () => { const botName = (await dialogs.prompt('Имя бота', 'My Bot')); if (!botName) return; const username = (await dialogs.prompt('Username бота, например my_helper_bot')); if (!username) return; setBusy(true); setFreshBotToken(null); try { const data = await api<{ bot: Bot; token: string }>('/bots', { method: 'POST', body: JSON.stringify({ displayName: botName, username }) }); setFreshBotToken(data.token); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось создать бота'); } finally { setBusy(false); } };
  const rotateBot = async (bot: Bot) => { if (!(await dialogs.confirm(`Перевыпустить токен @${bot.username}?`))) return; try { const data = await api<{ token: string }>(`/bots/${bot.id}/rotate-token`, { method: 'POST' }); setFreshBotToken(data.token); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось перевыпустить токен'); } };
  const exportData = async () => { setBusy(true); try { const response = await fetch(`${API_URL}/me/export`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error('Экспорт не готов'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `messenger-export-${me.username}.json`; a.click(); URL.revokeObjectURL(url); } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка экспорта'); } finally { setBusy(false); } };

  const privacySelect = (label: string, key: 'lastSeen' | 'calls' | 'groups') => <label>{label}<select value={privacy[key]} onChange={(e) => void savePrivacy({ [key]: e.target.value as PrivacySettings[typeof key] })}><option value="everyone">Все</option><option value="contacts">Только контакты</option><option value="nobody">Никто</option></select></label>;

  return <Modal onClose={onClose}><section className="settingsModal megaSettings">
    <header><div><span className="eyebrow">ТВОЁ ПРОСТРАНСТВО</span><h2>Настройки</h2></div><button onClick={onClose}>×</button></header>
    {error && <div className="errorBox">{error}</div>}
<div className="settingsLayout"><nav className="settingsNavigation" aria-label="Разделы настроек"><button className={page === 'profile' ? 'active' : ''} aria-current={page === 'profile' ? 'page' : undefined} onClick={() => setPage('profile')}>Профиль</button><button className={page === 'security' ? 'active' : ''} aria-current={page === 'security' ? 'page' : undefined} onClick={() => setPage('security')}>Безопасность</button><button className={page === 'privacy' ? 'active' : ''} aria-current={page === 'privacy' ? 'page' : undefined} onClick={() => setPage('privacy')}>Приватность</button><button className={page === 'appearance' ? 'active' : ''} aria-current={page === 'appearance' ? 'page' : undefined} onClick={() => setPage('appearance')}>Оформление</button><button className={page === 'devices' ? 'active' : ''} aria-current={page === 'devices' ? 'page' : undefined} onClick={() => setPage('devices')}>Устройства</button><button className={page === 'bots' ? 'active' : ''} aria-current={page === 'bots' ? 'page' : undefined} onClick={() => setPage('bots')}>Боты и Mini Apps</button><button className={page === 'blocked' ? 'active' : ''} aria-current={page === 'blocked' ? 'page' : undefined} onClick={() => setPage('blocked')}>Заблокированные</button><button className={page === 'data' ? 'active' : ''} aria-current={page === 'data' ? 'page' : undefined} onClick={() => setPage('data')}>Данные</button></nav><div className="settingsContent">{page === 'profile' && <>    <section className="profileEditor"><input ref={avatarInput} type="file" accept="image/*" hidden onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadAvatar(file); }} /><button className="avatarEdit" onClick={() => avatarInput.current?.click()} disabled={busy}><Avatar token={token} name={displayName || me.displayName} mediaId={avatarMediaId} className="profileEditAvatar" /><span>Изменить</span></button><div className="profileFields"><label>Имя<input value={displayName} onChange={(e) => setDisplayName(e.target.value)} maxLength={48} /></label><label>О себе<textarea value={bio} onChange={(e) => setBio(e.target.value)} maxLength={160} /></label></div></section>
    <button className="primaryButton profileSave" disabled={busy} onClick={() => void saveProfile()}>Сохранить профиль</button>

    </>}{page === 'security' && <><div className="settingsHeadingRow"><div><h3 className="settingsTitle">Безопасность</h3><p className="muted">Защити аккаунт кодом аутентификатора или ключом устройства.</p></div></div>
    <div className="securityCards"><div className="securityCard"><b>Двухфакторная проверка</b><span>{security.twoFactorEnabled ? 'Включена' : 'Выключена'}</span>{security.twoFactorEnabled ? <button onClick={() => void disable2fa()}>Отключить</button> : <button onClick={() => void start2fa()}>Включить</button>}</div><div className="securityCard"><b>Passkeys</b><span>{security.passkeys.length} ключей</span><button onClick={() => void addPasskey()}>＋ Passkey</button></div></div>
    {totpSetup && <div className="totpSetup"><b>Добавь секрет в Authenticator</b><code>{totpSetup.secret}</code><small>{totpSetup.uri}</small><div><input value={totpCode} inputMode="numeric" maxLength={6} onChange={(e) => setTotpCode(e.target.value.replace(/\D/g, '').slice(0, 6))} placeholder="000000" /><button className="smallPrimary" onClick={() => void confirm2fa()}>Подтвердить</button></div></div>}
    {!!recoveryCodes.length && <div className="totpSetup"><b>Коды восстановления — сохрани сейчас</b><span>Каждый код можно использовать один раз. Они помогут войти, если аутентификатор недоступен.</span><code>{recoveryCodes.join(' · ')}</code><button className="secondaryButton" onClick={() => void navigator.clipboard.writeText(recoveryCodes.join('\n'))}>Скопировать коды</button><button className="secondaryButton" onClick={() => setRecoveryCodes([])}>Я сохранил коды</button></div>}
    {!!security.passkeys.length && <div className="passkeyList">{security.passkeys.map((key) => <div className="passkeyCard" key={key.id}><div><b>{key.name}</b><span>{key.deviceType}{key.backedUp ? ' · synced' : ''} · {formatRelative(key.lastUsedAt || key.createdAt)}</span></div><button onClick={() => void removePasskey(key.id)}>Удалить</button></div>)}</div>}

    </>}{page === 'privacy' && <><h3 className="settingsTitle">Приватность</h3><div className="privacyGrid">{privacySelect('Кто видит online / last seen', 'lastSeen')}{privacySelect('Кто может звонить', 'calls')}{privacySelect('Кто может добавлять в группы', 'groups')}<label className="toggleSetting"><input type="checkbox" checked={privacy.readReceipts} onChange={(e) => void savePrivacy({ readReceipts: e.target.checked })} />Отчёты о прочтении</label></div>

    </>}{page === 'appearance' && <><h3 className="settingsTitle">Оформление</h3><div className="themePicker"><button className={theme === 'midnight' ? 'active' : ''} onClick={() => setTheme('midnight')}>Midnight</button><button className={theme === 'graphite' ? 'active' : ''} onClick={() => setTheme('graphite')}>Graphite</button><button className={theme === 'light' ? 'active' : ''} onClick={() => setTheme('light')}>Light</button></div>

    </>}{page === 'devices' && <><h3 className="settingsTitle">Устройства и сессии</h3><div className="sessionList">{sessions.map((session) => <div key={session.id} className={`sessionCard ${session.current ? 'current' : ''}`}><div className="sessionIcon">{deviceIcon(session.userAgent)}</div><div className="sessionInfo"><div><strong>{deviceName(session.userAgent)}</strong>{session.current && <b>Текущая</b>}</div><span>{session.ipAddress || 'Local'} · {formatRelative(session.lastSeenAt)}</span></div>{!session.current && <button disabled={busy} onClick={() => void terminate(session.id)}>Завершить</button>}</div>)}</div><button className="dangerButton" disabled={busy || sessions.filter((x) => !x.current).length === 0} onClick={() => void terminateOthers()}>Завершить все другие сессии</button>

    </>}{page === 'bots' && <><div className="settingsHeadingRow"><div><h3 className="settingsTitle">Боты и API</h3><p className="muted">Bot API, webhooks и Mini Apps.</p></div><button className="smallPrimary" onClick={() => void createBot()}>＋ Бот</button></div>{freshBotToken && <div className="tokenReveal"><b>Новый токен</b><code>{freshBotToken}</code><button onClick={() => navigator.clipboard?.writeText(freshBotToken)}>Копировать</button></div>}<div className="botList">{bots.length ? bots.map((bot) => <div className="botCard" key={bot.id}><div className="botGlyph">BOT</div><div><strong>{bot.displayName}</strong><span>@{bot.username}</span><code>{bot.tokenPrefix}…</code></div><button onClick={() => void rotateBot(bot)}>Новый токен</button></div>) : <p className="muted">Ботов пока нет.</p>}</div>

    </>}{page === 'blocked' && <><h3 className="settingsTitle">Заблокированные</h3><div className="blockedList">{blockedUsers.length ? blockedUsers.map((user) => <div className="blockedCard" key={user.id}><Avatar token={token} name={user.displayName} mediaId={user.avatarMediaId} className="memberAvatar" /><div><strong>{user.displayName}</strong><span>@{user.username}</span></div><button onClick={() => void unblock(user)}>Разблокировать</button></div>) : <p className="muted">Список пуст.</p>}</div>

    </>}{page === 'data' && <><div className="securityCard"><b>Уведомления</b><span>Разреши уведомления, чтобы получать сообщения вне приложения.</span><button onClick={async () => { if ('Notification' in window && !('__TAURI_INTERNALS__' in window)) { const result = await Notification.requestPermission(); if (result !== 'granted') setError('Уведомления выключены в настройках устройства.'); } window.dispatchEvent(new Event('messenger:enable-push')); }}>Включить уведомления</button></div><div className="settingsHeadingRow"><div><h3 className="settingsTitle">Данные и уведомления</h3><p className="muted">Экспорт переписки и управление уведомлениями на этом устройстве.</p></div><button className="smallPrimary" disabled={busy} onClick={() => void exportData()}>Экспортировать</button></div></>}</div></div>
  </section></Modal>;
}

